# Generated by Django 2.2 on 2019-04-08 09:28

from django.db import migrations, models
import django.db.models.deletion
import jogging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('role', models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('M', 'Manager')], default='U', max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.IntegerField(validators=[jogging.models.validate_positive])),
                ('time', models.IntegerField(validators=[jogging.models.validate_positive])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogging.User')),
            ],
        ),
    ]
