# Generated by Django 2.2 on 2019-04-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0002_auto_20190408_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='user',
        ),
    ]
